### ISSUE TITLE
UI: Agree on wording of "Sign Up, Sign Out or Log Out, Sign In or Log In" and implement wording

### ISSUE THREAD

**Issue by ethanstrominger** [reach4help/reach4help#1179] opened 2021-02-16 19:07 UTC
Update menus to be consistent.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1179)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by shayantist** [comment] 2021-02-18 08:48
Duplicate of #1171

**Closed as completed by shayantist** 2021-02-18 08:48 UTC
Labels: duplicate
