### ISSUE TITLE
UI feedback needed: Add "Contact Us"

### ISSUE THREAD

**Issue by ethanstrominger** [reach4help/reach4help#1214] opened 2021-03-07 14:49 UTC
--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1214)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by shayantist** [comment] 2021-04-12 07:09
Closing this since it looks like a duplicate of #1207

**Closed as completed by shayantist** 2021-04-12 07:09 UTC
