### ISSUE TITLE
[BUG]  Request Timeline Page:  "phone icon is disabled"

### ISSUE THREAD

**Issue by punita123** [reach4help/reach4help#697] opened 2020-06-11 16:41 UTC
**Describe the bug**
On the "Request Timeline Page'  "the phone icon is disabled.

To Reproduce**
1. Go to 'https://reach4help-staging-web-client.firebaseapp.com/timeline/ryjNLSLAGB2fqPZHV8uM...'
2. Click on 'phone icon'
3. Phone icon is disabled 

**Expected behavior**
Phone Icon should be working.

**Screenshots**
![image](https://user-images.githubusercontent.com/65728782/84415309-95a71300-abe0-11ea-93a2-71e4be9e6d40.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser  chrome
 - Version [ 83.0.4103.97 (Official Build) (64-bit]

**Additional context**
N/A

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/697)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by CorporateInvesther** [comment] 2020-06-12 15:32
Closed, duplicate of 696

**Closed by CorporateInvesther** 2020-06-12 15:32 UTC
Labels: BUG
