### ISSUE TITLE
vm

### ISSUE THREAD

**Issue by mnznz** [reach4help/reach4help#930] opened 2020-08-29 10:50 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/930)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by mnznz** [comment] 2020-08-29 10:50
ok

**Comment by schowdhury8** [comment] 2020-08-31 08:59
Hi @mnznz , not quite sure what the issue is here so I'll be closing it. If you actually have an issue, feel free to reopen and edit it with the appropriate info.

**Closed by schowdhury8** 2020-08-31 08:59 UTC
